apiVersion: v1
kind: Service
metadata:
  labels:
    app: openshift-training-nestjs
    team: ibm-training
  name: openshift-training-nestjs
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    team: ibm-training

